### ISSUE TITLE
api test causes panic

### ISSUE THREAD

**Issue by xcodersun** [xcodersun/eywa#19]
$ ./auto_test.sh -vif -T ApiToDevice -n 1
Warn: EYWA_HOME is not set. Using current directory as EYWA_HOME.
Running test setup...
Starting test server...
Test server started...
Starting Tests...
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0x75aafa]

goroutine 41 [running]:
panic(0xa41ec0, 0xc420012090)
	/home/ec2-user/.gvm/gos/go1.7.3/src/runtime/panic.go:500 +0x1a1
github.com/eywa/message_handlers.glob..func1.1(0xff61a0, 0xc4201295f0, 0xff5640, 0xc42023da90, 0xfed100, 0xc4202146f0)
	/home/ec2-user/.gvm/pkgsets/go1.7.3/global/src/github.com/eywa/message_handlers/indexer.go:41 +0xa5a
created by github.com/eywa/connections.(*WebsocketConnection).start
	/home/ec2-user/.gvm/pkgsets/go1.7.3/global/src/github.com/eywa/connections/websocket_connection.go:371 +0x10c
.--- FAIL: TestApiToDevice (0.25s)
FAIL	github.com/eywa/api_tests	0.258s

**Comment by xcodersun** [comment]
First of all, by looking at elasticsearch log, it shows I was missing mapper-size plugin
[2016-12-25 17:31:26,535][DEBUG][action.admin.indices.create] [Elizabeth "Betsy" Braddock] [channels.2.2016-51] failed to create
MapperParsingException[Failed to parse mapping [activities]: Root mapping definition has unsupported parameters:  [_size : {enabled=false}]]; nested: MapperParsingException[Root mapping definition has unsupported parameters:  [_size : {enabled=false}]];

However, after installing mapper-size, I still see the panic in the test.
